version: '4'

networks:
  default:
    name: inception_network

volumes:
  wordpress_data:
    name: inception_wordpress_volume
  mariadb_data:
    name: inception_mariadb_volume

services:
  mariadb_service: ### MariaDB ###
    image: inception_mariadb
    container_name: inception_mariadb_container
    networks:
      - default
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
    env_file: .env
    expose:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/health_check.sh"]
      interval: 10s
      timeout: 1m
      retries: 5

  wordpress_service: ### WordPress ###
    image: inception_wordpress  
    container_name: inception_wordpress_container
    networks:
      - default
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
        mariadb_service:
          condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html

  nginx_service: ### Nginx ###
    image: inception_nginx
    container_name: inception_nginx_container
    networks:
      - default
    depends_on:
      - wordpress_service
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html