version: '3.8'

networks:
  default:
    driver: bridge
    name: inception_network

volumes:
  wordpress_data:
    name: inception_wordpress_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress
  mariadb_data:
    name: inception_mariadb_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/mariadb

services:
  mariadb_service: ### MariaDB ###
    image: inception_mariadb
    container_name: inception_mariadb_container
    networks:
      - default
    hostname: ${MYSQL_HOST}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
    expose:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/health_check.sh"]
      interval: 10s
      timeout: 1m
      retries: 5

  wordpress_service: ### WordPress ###
    image: inception_wordpress  
    container_name: inception_wordpress_container
    networks:
      - default
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - WP_USER_USER=${WP_USER_USER}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
    depends_on:
        mariadb_service:
          condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wordpress_data:/var/www/html

  nginx_service: ### Nginx ###
    image: inception_nginx
    container_name: inception_nginx_container
    networks:
      - default
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_CERTIFICATE=${SSL_CERTIFICATE}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
      - MYSQL_HOST=${MYSQL_HOST}
    depends_on:
      - wordpress_service
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    extra_hosts:
      - "maroy.42.qc:127.0.0.1"