version: '3.8'

networks:
  default:
    driver: bridge
    name: inception_network

volumes:
  wordpress_data:
    name: inception_wordpress_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/wordpress
  mariadb_data:
    name: inception_mariadb_volume
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${VOLUMES_PATH}/mariadb

services:
  mariadb_service: ### MariaDB ###
    image: inception_mariadb
    container_name: inception_mariadb_container
    networks:
      - default
    hostname: ${MYSQL_HOST}
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    build: 
      context: requirements/mariadb/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  wordpress_service: ### WordPress ###
    image: inception_wordpress  
    container_name: inception_wordpress_container
    networks:
      - default
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_HOST=${MYSQL_HOST}
      - WP_USER_USER=${WP_USER_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
    secrets:
      - db_password
      - db_root_password
      - wp_password
      - wp_root_password
    depends_on:
      - mariadb_service
    ports:
      - "9000:9000"
    volumes:
      - wordpress_data:/var/www/html

  nginx_service: ### Nginx ###
    image: inception_nginx
    container_name: inception_nginx_container
    networks:
      - default
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      - SSL_CERTIFICATE=${SSL_CERTIFICATE}
      - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY}
      - MYSQL_HOST=${MYSQL_HOST}
    depends_on:
      - wordpress_service
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    extra_hosts:
      - "${DOMAIN_NAME}:127.0.0.1"

secrets:
  db_password:
    file: ${SECRETS_PATH}/db_password.txt
  db_root_password:
    file: ${SECRETS_PATH}/db_root_password.txt
  wp_password:
    file: ${SECRETS_PATH}/wp_password.txt
  wp_root_password:
    file: ${SECRETS_PATH}/wp_root_password.txt